# Generated by Django 3.1.2 on 2020-11-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField()),
                ('Address', models.CharField(max_length=1000)),
                ('zone', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=1000)),
                ('method', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'PEOPLE',
            },
        ),
    ]
